class CustomerModel {
  late String customerFullName,
      phoneNumber,
      type,
      profilePicture,
      emailAddress,
      customerAddress,
      dueAmount,
      openingBalance,
      remainedBalance,
      billingPinCod,
      gstNumber,
      billingCity,
      billingState,
      billingZip,
      shippingName,
      shippingAddress,
      shippingPINCOD,
      shippingLandmark,
      shippingState,
      shippingPhoneNumber;

  CustomerModel({
    required this.customerFullName,
    required this.phoneNumber,
    required this.type,
    required this.profilePicture,
    required this.emailAddress,
    required this.customerAddress,
    required this.dueAmount,
    required this.openingBalance,
    required this.remainedBalance,
    required this.billingCity,
    required this.billingPinCod,
    required this.billingState,
    required this.billingZip,
    required this.gstNumber,
    required this.shippingAddress,
    required this.shippingLandmark,
    required this.shippingName,
    required this.shippingPhoneNumber,
    required this.shippingPINCOD,
    required this.shippingState,
  });
  Map<dynamic, dynamic> toJson() => <dynamic, dynamic>{
        'customerFullName': customerFullName,
        'phoneNumber': phoneNumber,
        'type': type,
        'profilePicture': profilePicture,
        'emailAddress': emailAddress,
        'customerAddress': customerAddress,
        'due': dueAmount,
        'openingBalance': openingBalance,
        'remainedBalance': remainedBalance,
        'billingCity': billingCity,
        'billingPinCod': billingPinCod,
        'billingState': billingState,
        'billingZip': billingZip,
        'gstNumber': gstNumber,
        'shippingAddress': shippingAddress,
        'shippingLandmark': shippingLandmark,
        'shippingName': shippingName,
        'shippingPhoneNumber': shippingPhoneNumber,
        'shippingPINCOD': shippingPINCOD,
        'shippingState': shippingState,
      };

  CustomerModel.fromJson(Map<dynamic, dynamic> json)
      : customerFullName = json['customerFullName'] as String,
        phoneNumber = json['phoneNumber'] as String,
        type = json['type'] as String,
        profilePicture = json['profilePicture'] as String,
        emailAddress = json['emailAddress'] as String,
        customerAddress = json['customerAddress'] as String,
        dueAmount = json['due'] as String,
        openingBalance = json['openingBalance'] as String,
        remainedBalance = json['remainedBalance'] as String,
        billingCity = json['billingCity'] as String,
        billingPinCod = json['billingPinCod'] as String,
        billingState = json['billingState'] as String,
        billingZip = json['billingZip'] as String,
        gstNumber = json['gstNumber'] as String,
        shippingAddress = json['shippingAddress'] as String,
        shippingLandmark = json['shippingLandmark'] as String,
        shippingName = json['shippingName'] as String,
        shippingPhoneNumber = json['shippingPhoneNumber'] as String,
        shippingPINCOD = json['shippingPINCOD'] as String,
        shippingState = json['shippingState'] as String;
}
